name = "eym-acc"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

[build]
command = "echo no-build"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
